import { describe, expect, it } from "vitest";
import componentsCss from "./components.css?raw";
import themesCss from "./themes.generated.css?raw";
import tokensCss from "./tokens.css?raw";
import shellCss from "../styles.css?raw";

const THEMES = [
  "system",
  "dark",
  "light",
  "aurora",
  "ember",
  "midnight",
  "ocean",
  "forest",
  "rose",
] as const;

const COLOR_MODES = ["color", "soft", "vivid", "no-color", "high-contrast"] as const;

describe("desktop design-system contracts", () => {
  it("ships every renderer-neutral theme and color treatment", () => {
    for (const theme of THEMES) {
      for (const mode of COLOR_MODES) {
        expect(themesCss).toContain(`[data-theme="${theme}"][data-color-mode="${mode}"]`);
      }
    }

    expect(themesCss.match(/--color-focus-ring:/g)).toHaveLength(THEMES.length * COLOR_MODES.length);
    expect(themesCss).toContain("@generated by autoharness-presentation");
  });

  it("keeps keyboard focus visible through the semantic two-layer ring", () => {
    expect(tokensCss).toContain("--focus-inner: var(--color-surface-base)");
    expect(tokensCss).toContain("--focus-outer: var(--color-focus-ring)");
    expect(shellCss).toMatch(/button:focus-visible,[\s\S]*outline: var\(--focus-width\) solid var\(--focus-outer\)/);
    expect(shellCss).toContain("box-shadow: 0 0 0 var(--focus-width) var(--focus-inner)");
    expect(componentsCss).toContain(".dsMenuItem:focus-visible");
    expect(componentsCss).toContain(".dsSplitHandle:focus-visible span");
  });

  it("freezes transitions and looping animation for either reduced-motion input", () => {
    expect(tokensCss).toContain('[data-reduce-motion="true"]');
    expect(tokensCss).toContain("@media (prefers-reduced-motion: reduce)");
    expect(tokensCss.match(/animation-iteration-count: 1 !important/g)).toHaveLength(2);
    expect(tokensCss.match(/transition-duration: 1ms !important/g)).toHaveLength(2);
  });

  it("preserves semantic state when color is unavailable", () => {
    expect(componentsCss).toContain('[data-color-mode="no-color"] .dsChip[data-intent="warning"] { border-style: dashed; }');
    expect(componentsCss).toContain('[data-color-mode="no-color"] .dsChip[data-intent="danger"] { border-style: double; }');
    expect(componentsCss).toContain('[data-color-mode="no-color"] .dsChip[data-intent="success"] { border-width: 2px; }');
    expect(componentsCss).toContain('[data-color-mode="high-contrast"] .dsButton');
  });

  it("defines each non-color token family required by the desktop shell", () => {
    for (const token of [
      "--font-prose",
      "--type-body",
      "--space-4",
      "--elevation-2",
      "--radius-md",
      "--focus-width",
      "--motion-fast",
      "--rail-width",
      "--conversation-measure",
    ]) {
      expect(tokensCss).toContain(`${token}:`);
    }
  });
});
