import { describe, expect, it } from "vitest";
import componentsCss from "./components.css?raw";
import themesCss from "./themes.generated.css?raw";
import tokensCss from "./tokens.css?raw";
import shellCss from "../styles.css?raw";

const THEMES = [
  "system",
  "dark",
  "light",
  "aurora",
  "ember",
  "midnight",
  "ocean",
  "forest",
  "rose",
] as const;

const COLOR_MODES = ["color", "soft", "vivid", "no-color", "high-contrast"] as const;

describe("desktop design-system contracts", () => {
  it("keeps menu descriptions and shortcuts readable on every selected surface", () => {
    const luminance = (hex: string) => {
      const channels = [1, 3, 5].map((offset) => parseInt(hex.slice(offset, offset + 2), 16) / 255);
      const linear = channels.map((channel) => channel <= 0.04045 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4);
      return linear[0] * 0.2126 + linear[1] * 0.7152 + linear[2] * 0.0722;
    };
    const contrast = (first: string, second: string) => {
      const [dark, light] = [luminance(first), luminance(second)].sort((a, b) => a - b);
      return (light + 0.05) / (dark + 0.05);
    };
    const themes = themesCss.split("}").filter((block) => block.includes("--color-surface-base:"));
    expect(themes).toHaveLength(45);
    for (const theme of themes) {
      const tokens = Object.fromEntries([...theme.matchAll(/--color-([\w-]+): (#[\da-f]{6})/g)].map((match) => [match[1], match[2]]));
      const selectedInk = theme.includes('data-color-mode="high-contrast"') ? tokens["text-on-accent"] : tokens["text-primary"];
      expect(contrast(selectedInk, tokens["surface-selected-muted"])).toBeGreaterThanOrEqual(4.5);
      expect(contrast(tokens["text-secondary"], tokens["surface-raised"])).toBeGreaterThanOrEqual(4.5);
    }
    expect(componentsCss).toContain('.dsMenuItem:is(:hover, :focus-visible, [data-active="true"]) :is(.dsMenuCopy small, .dsMenuIcon, kbd) { color: inherit; }');
    expect(componentsCss).toContain('[data-color-mode="high-contrast"] .dsMenuItem:is(:hover, :focus-visible, [data-active="true"]) { color: var(--color-text-on-accent); }');
  });

  it("ships every renderer-neutral theme and color treatment", () => {
    for (const theme of THEMES) {
      for (const mode of COLOR_MODES) {
        expect(themesCss).toContain(`[data-theme="${theme}"][data-color-mode="${mode}"]`);
      }
    }

    expect(themesCss.match(/--color-focus-ring:/g)).toHaveLength(THEMES.length * COLOR_MODES.length);
    expect(themesCss).toContain("@generated by autoharness-presentation");
  });

  it("keeps keyboard focus visible through the semantic two-layer ring", () => {
    expect(tokensCss).toContain("--focus-inner: var(--color-surface-base)");
    expect(tokensCss).toContain("--focus-outer: var(--color-focus-ring)");
    expect(shellCss).toMatch(/button:focus-visible,[\s\S]*outline: var\(--focus-width\) solid var\(--focus-outer\)/);
    expect(shellCss).toContain("box-shadow: 0 0 0 var(--focus-width) var(--focus-inner)");
    expect(componentsCss).toContain(".dsMenuItem:focus-visible");
    expect(componentsCss).toContain(".dsSplitHandle:focus-visible span");
  });

  it("freezes transitions and looping animation for either reduced-motion input", () => {
    expect(tokensCss).toContain('[data-reduce-motion="true"]');
    expect(tokensCss).toContain("@media (prefers-reduced-motion: reduce)");
    expect(tokensCss.match(/animation-iteration-count: 1 !important/g)).toHaveLength(2);
    expect(tokensCss.match(/transition-duration: 1ms !important/g)).toHaveLength(2);
  });

  it("preserves semantic state when color is unavailable", () => {
    expect(componentsCss).toContain('[data-color-mode="no-color"] .dsChip[data-intent="warning"] { border-style: dashed; }');
    expect(componentsCss).toContain('[data-color-mode="no-color"] .dsChip[data-intent="danger"] { border-style: double; }');
    expect(componentsCss).toContain('[data-color-mode="no-color"] .dsChip[data-intent="success"] { border-width: 2px; }');
    expect(componentsCss).toContain('[data-color-mode="high-contrast"] .dsButton');
  });

  it("defines each non-color token family required by the desktop shell", () => {
    for (const token of [
      "--font-prose",
      "--type-body",
      "--space-4",
      "--elevation-2",
      "--radius-md",
      "--focus-width",
      "--motion-fast",
      "--rail-width",
      "--conversation-measure",
    ]) {
      expect(tokensCss).toContain(`${token}:`);
    }
  });
});
